      character in_data_maskname*200
      parameter(in_data_maskname=
     &  '/home/ggpjv/genie/'//
     &  'genie-igcm3/data/input'//
     &  '/landmask_std_t42.nc')
      character in_mask_varname*200
      parameter(in_mask_varname=
     &  'lsm')

      character out_data_filename_2*200
      parameter(out_data_filename_2=
     &  '/home/ggpjv/genie/genie-utilities/data/output/'//
     &                   'runoff_t42.nc')


