      character in_temp_filename*200
      parameter(in_temp_filename=
     &  '/home/ggdjl/genie/genie-utilities/data/input/'//
     &                   'xakxd_temp1_ann.nc')
      character in_temp_varname*200
      parameter(in_temp_varname=
     &  'temp_1')

      character in_lsm_filename*200
      parameter(in_lsm_filename=
     &  '/home/ggdjl/genie/genie-utilities/data/input/'//
     &                   'xakxd_lsm.nc')
      character in_lsm_varname*200
      parameter(in_lsm_varname=
     &  'lsm')


      character out_data_filename*200
      parameter(out_data_filename=
     &  '/home/ggdjl/genie/genie-utilities/data/output/'//
     &                   'xakxd_goldstein.nc')

      character out_ascii_filename*200
      parameter(out_ascii_filename=
     &  '/home/ggdjl/genie/genie-utilities/data/output/'//
     &                   'xakxd_goldstein.dat')
